name: Deploy to server

on:
  push:
    branches:
      - auto-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          
      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd crm-frontend
            git pull origin auto-deploy
            npm install
            npm run build
            pm2 reload CRMAPP3131
          EOF
