name: Frontend CI/CD

on:
  push:
    branches:
      # - main
      - test
      # - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repositoryni clone qilish
        uses: actions/checkout@v3

      - name: Node.js o‘rnatish
        uses: actions/setup-node@v3
        with:
          node-version: 'v20.12.2'

      - name: Dependency'larni o‘rnatish
        run: npm install

      - name: Build yaratish
        run: npm run build

      - name: Serverga fayllarni yuborish
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # NVM o'rnatilganligini tekshirish va kerakli Node.js versiyasini tanlash
            if [ ! -d "$HOME/.nvm" ]; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
              source ~/.nvm/nvm.sh
            else
              source ~/.nvm/nvm.sh
            fi
            nvm use 20.10.0

            # Loyihaning joylashuvini yaratish va loyihani olish
            mkdir -p /projects/crm-front/${{ secrets.REPO_NAME }}
            cd /projects/crm-front/${{ secrets.REPO_NAME }}

            if [ ! -d ".git" ]; then
                git clone --branch main https://test.soff.uz/:${{ secrets.TOKEN_GITHUB }}@github.com/Soff-Hub/${{ secrets.REPO_NAME }}.git .
            else
                git pull origin test
            fi

      - name: Deploy to development server (for dev branch)
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.DEV_SERVER_IP }}
          username: root
          password: ${{ secrets.DEV_SERVER_PASSWORD }}
          script: |
            # NVM o'rnatilganligini tekshirish va kerakli Node.js versiyasini tanlash
            if [ ! -d "$HOME/.nvm" ]; then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
              source ~/.nvm/nvm.sh
            else
              source ~/.nvm/nvm.sh
            fi
            nvm use 20.10.0

            # Loyihaning joylashuvini yaratish va loyihani olish
            mkdir -p /projects/crm-front/${{ secrets.REPO_NAME }}
            cd /projects/crm-front/${{ secrets.REPO_NAME }}
            if [ ! -d ".git" ]; then
                git clone --branch dev https://dynamicuz:${{ secrets.TOKEN_GITHUB }}@github.com/Soff-Hub/${{ secrets.REPO_NAME }}.git .
            else
                git pull origin dev
            fi

            # Kerakli kutubxonalarni o'rnatish va loyihani build qilish
            npm install
            npm run build

            # PM2 orqali jarayonlarni boshqarish
            pm2 restart ${{ secrets.REPO_NAME }}-dev || pm2 start npm --name="${{ secrets.REPO_NAME }}-dev" -- run start
            pm2 save
